### ISSUE TITLE
The Plugin Crashed and Kicked all Player

### ISSUE THREAD

**Issue by DragonfireHD** [Chalapa13/WorldGuard#77]
The Plugin has a Problem until 30 minutes server playing crasht the server from Worldquard plugin the plugin Reload my server and crasht the server

Please fix then 
New Version problem on Evenlistiner 327 and Worldquard.php line 177 Problem

**Comment by awgybop1** [comment]
Hello, DragonfireHD! Sorry about that, this was a bug in that version of the plugin. This has been fixed in the latest release, however has not yet been approved on Poggit unfortunately. You can join the [Discord](https://discordapp.com/invite/uZevqGX) and we can give you the latest version of the plugin with the newest updates, features, and fixes!
